FROM python:3.9-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend /app

# Start Celery beat (scheduler)
CMD ["celery", "-A", "celery_beat.celery", "beat", "--loglevel=info"]
